name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          python: 3.7
          packaging: linux
        - os: windows-latest
          python: 3.9
          packaging: win

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - uses: actions/cache@v2
      with:
        key: ${{matrix.os}}-${{matrix.python}}-${{env.BUILD_TYPE}}-${{hashFiles('**/CMakeLists.txt')}}
        path: |
          ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DZENO_BUILD_TESTS:BOOL=ON ${{matrix.options}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test Import ZENO DLLs
      run: python -c "import zenqt.system.dll"

    - name: Integrated Test
      if: ${{ matrix.os != 'windows-latest' }}  # TODO: fix windows test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    #- name: Install Python Packages
    #  run: |
    #    python -m pip install --upgrade pip
    #    python -m pip install pybind11 numpy PySide2 pyinstaller

    #- name: Packaging via PyInstaller
    #  if: ${{ matrix.packaging }}
    #  run: python -m PyInstaller scripts/launcher_${{matrix.packaging}}.spec

    #- name: Upload Artifact
    #  if: ${{ matrix.packaging }}
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: launcher-${{matrix.packaging}}
    #    path: dist/launcher
