name: Intergrated Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04  # cihou linuxdeployqt
          cmake_args: -DCMAKE_CXX_COMPILER=g++-9
        - os: windows-latest

    runs-on: ${{ matrix.os }}
    #continue-on-error: true

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.cmake_args}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
