name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
        #- os: ubuntu-latest
        #  python: 3.8
        #  container: archibate/zeno_build:latest
        #  options: -DEXTENSION_zenvdb:BOOL=ON -DEXTENSION_FastFLIP:BOOL=ON -DZENOFX_ENABLE_OPENVDB:BOOL=ON
        #- os: ubuntu-18.04
        #  python: 3.6
        - os: ubuntu-latest
          python: 3.7
        - os: windows-latest
          python: 3.9

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Update pip and Install Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11 numpy PySide2 pyinstaller

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DZENO_BUILD_TESTS:BOOL=ON ${{matrix.options}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test Import ZENO
      run: python -c "import zenqt.system.dll"

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Packaging (Windows)
      if: matrix.config.os == 'windows-latest'
      run: python -m PyInstaller scripts\zeno_win.spec

    - name: Packaging (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      run: python -m PyInstaller scripts\zeno_linux.spec

    - name: Upload Artifact (Windows)
      if: matrix.config.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: zenqt-win
        path: dist/zeno

    - name: Upload Artifact (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: zenqt-win
        path: dist/zeno
