name: Automated Release

on:
  push:
    tags: [ 'v*' ]

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: rel-${{ github.ref }}
        release_name: rel-${{ github.ref }}
        body: "(Automated Release by Github Actions)"

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: windows-latest

    needs: release
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: build/bin/citest

    - name: Packaging
      id: packaging
      run: python .packaging.py

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/citest.zip
        asset_name: citest-${{ github.ref }}-${{ steps.packaging.outputs.arch }}.zip
        asset_content_type: application/zip
