name: Automated Release

on:
  #schedule:
  #- cron: '0 8 * * 6'  # Release at Beijing Time 16:00 Sat
  push:
    branches: [ zeno2 ]
    #branches: [ stable ]
    #tags: [ 'v*' ]

env:
  BUILD_TYPE: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get Date
      id: get_date
      run: python -c "import datetime; d = datetime.datetime.now(); print('::set-output name=date::{}.{}.{}'.format(d.year, d.month, d.day))"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: ${{ steps.get_date.outputs.date }}
        release_name: ${{ steps.get_date.outputs.date }}
        body: "(Automated Release by Github Actions)\n\n- branch ${{ github.ref }}\n- commit ${{ github.sha }}\n- date ${{ steps.get_date.outputs.date }}\n\nWindows: After download, extract the zip file to a directory, then double-click the file `000_start.bat` in that directory to start our application. Alternatively you may manually run `zenoedit.exe`. If you encounter bugs, please let us know by submitting [a Github Issue](https://github.com/zenustech/zeno/issues), thank for your support!\n\nLinux: The released binary support Ubuntu 18.04 and above, otherwise please build from source. Extract the downloaded tar.gz to a directory, then run `bash 000_start.sh` in that directory to start our application. Alternatively you may manually run `usr/bin/zenoedit`, or simply extract it to the root so that it is `/usr/bin/zenoedit`. Try `chmod +x usr/bin/*` if they don't have execute permission.\n\n(由 GitHub CI/CD 自动化发布)\n\nWindows: 下载后，把 zip 文件解压到一个目录，然后双击其中的 `000_start.bat` 这个文件，即可启动我们的程序。此外您也可以找到 `zenoedit.exe` 直接双击运行。如果您遇到了 BUG，请通过提交 [Github Issue](https://github.com/zenustech/zeno/issues) 的方式来反馈给我们, 感谢您的支持！\n\nLinux: 发布的二进制版支持 Ubuntu 18.04 以上的系统，否则请从源码构建。把下载的 tar.gz 文件解压到一个目录，然后在那个目录中运行命令 `bash 000_start.sh` 即可启动我们的程序。此外您也可以直接运行 `usr/bin/zenoedit，或者直接把 tar.gz 文件解压到根目录变成 `/usr/bin/zenoedit`。如果遇到没有执行权限的问题可以试试看 `chmod +x usr/bin/*`。"

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04  # cihou linuxdeployqt
          cmake_args: -DCMAKE_CXX_COMPILER=g++-9
        - os: windows-latest

    needs: release
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.cmake_args}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Packaging
      run: python misc/ci/package.py

    - name: Versioning
      id: versioning
      run: python misc/ci/get_ver.py

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/build/bin.${{ steps.versioning.outputs.fileext }}
        asset_name: zeno-${{ steps.versioning.outputs.filename }}.${{ steps.versioning.outputs.fileext }}
        asset_content_type: ${{ steps.versioning.outputs.mimetype }}

    - name: Upload To Server
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        ARGS: '-rltgoDzvO --delete'
        SOURCE: ${{github.workspace}}/build/bin.zip
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}/zeno-${{ steps.versioning.outputs.filename }}.${{ steps.versioning.outputs.fileext }}
